=== hmrc/business-details-api/resources/public/api/conf/1.0/schemas/retrieveBusinessDetails/retrieve_business_details_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Retrieve additional information for a user's business details",
  "description": "Retrieve business details response",
  "type": "object",
  "properties": {
    "businessId": {
      "type": "string",
      "description": "A unique identifier for the business income source.",
      "example": "XAIS12345678910"
    },
    "typeOfBusiness": {
      "type": "string",
      "description": "The type of business income source. ",
      "enum": [
        "self-employment",
        "uk-property",
        "foreign-property",
        "property-unspecified"
      ]
    },
    "tradingName": {
      "type": "string",
      "description": "The trading name of the business.",
      "example": "ABC Ltd."
    },
    "accountingPeriods": {
      "type": "array",
      "description": "A list of the accounting periods for the business",
      "items": {
        "type": "object",
        "properties": {
          "start": {
            "description": "Date your books or accounts start - the beginning of your accounting period.",
            "type": "string",
            "example": "2018-04-06"
          },
          "end": {
            "description": "Date your books or accounts are made up to - the end of your accounting period.",
            "type": "string",
            "example": "2019-04-05"
          }
        },
        "required": [
          "start",
          "end"
        ]
      }
    },
    "accountingType": {
      "description": "CASH if you used the cash basis, money actually received and paid out, to calculate your income and expenses. Otherwise ACCRUALS.",
      "type": "string",
      "enum": [
        "CASH",
        "ACCRUALS"
      ]
    },
    "commencementDate": {
      "description": "Business start date, must be in the past.",
      "type": "string",
      "example": "2016-09-24"
    },
    "cessationDate": {
      "description": "Business cessation date.",
      "type": "string",
      "example": "2020-03-24"
    },
    "businessAddressLineOne": {
      "description": "First line of the business address.",
      "type": "string",
      "example": "1 ABC Rd."
    },
    "businessAddressLineTwo": {
      "description": "Second line of the business address.",
      "type": "string",
      "example": "London"
    },
    "businessAddressLineThree": {
      "description": "Third line of the business address.",
      "type": "string",
      "example": "Greater London"
    },
    "businessAddressLineFour": {
      "description": "Fourth line of the business address.",
      "type": "string",
      "example": "United Kingdom"
    },
    "businessAddressPostcode": {
      "description": "Business code.",
      "type": "string",
      "example": "M1 1AG"
    },
    "businessAddressCountryCode": {
      "description": "The two letter code for a country must adhere to ISO 3166.",
      "type": "string",
      "example": "GB"
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "A list of endpoint links that indicate possible actions related to the current resource",
        "properties": {
          "href": {
            "description": "The relative url of the endpoint",
            "type": "string",
            "example": "/individuals/business/details/CX897463D/XAIS123456789012"
          },
          "rel": {
            "description": "A label for the endpoint, which describes how it is related to the current resource\nThe rel will be self where the action is retrieval of the same resource",
            "type": "string",
            "enum": [
              "self"
            ]
          },
          "method": {
            "description": "The HTTP method type for the endpoint",
            "type": "string",
            "enum": [
              "GET"
            ]
          }
        },
        "required": [
          "href",
          "rel",
          "method"
        ]
      }
    }
  },
  "required": [
    "businessId",
    "typeOfBusiness",
    "accountingPeriods"
  ]
}

=== hmrc/business-details-api/resources/public/api/conf/1.0/examples/retrieveBusinessDetails/retrieve_business_details_response.json
{
  "businessId": "XAIS12345678910",
  "typeOfBusiness": "self-employment",
  "tradingName": "Aardvark Window Cleaning Services",
  "accountingPeriods":
  [
    {
      "start": "2018-04-06",
      "end": "2019-04-05"
    }
  ],
  "accountingType": "ACCRUALS",
  "commencementDate": "2016-09-24",
  "cessationDate": "2020-03-24",
  "businessAddressLineOne": "6 Harpic Drive",
  "businessAddressLineTwo": "Domestos Wood",
  "businessAddressLineThree": "ToiletDucktown",
  "businessAddressLineFour": "CIFSHIRE",
  "businessAddressPostcode": "SW4F 3GA",
  "businessAddressCountryCode": "GB"
}
